### ISSUE TITLE
hotkeys stop working

### ISSUE THREAD

**Issue by netfun81** [phillbush/shod#1]
I like your window manager and the way it tabs and tiles.  I have an issue which ive duplicated using both sxhkd and xbindkeys.  If creating several tab windows and then closing them quickly the hotkey program will stop responding and then no other hotkeys will work.  I didnt notice that happen with only floating containers that contain no other windows.

**Comment by phillbush** [comment]
I just checked the code and realized that I forgot to call XUngrabPointer(3) after calling XGrabPointer(3) in one of the mouse related functions. [This commit](https://github.com/phillbush/shod2/commit/33d7a5559bd7523f187e369d16ac9fc5d9e04dfd) fixes that.

Maybe the keybinding programs refused to work because the pointer was grabbed.  
I could not reproduce this bug on my system. Can you check if it works now for you?

**Comment by netfun81** [comment]
I tried the update from today and seems to be working good.  Thank you!
