### ISSUE TITLE
feature request: more shodc/xres bar control

### ISSUE THREAD

**Issue by sewnie** [phillbush/shod#34]
my feature request is to implement a command in `shodc` or some flag, to control the bar to set it's position, set its state - hidden or visible, or to make it not take window space, appear below or above windows.

for me i find the bar a bit big in my workflow, and though thats unavoidable i'm used to toggle the bar in my previous dwm setup.

**Comment by BanchouBoo** [comment]
As somebody who also uses this in my dwm setup, it's important to add that you can toggle the bar visibilty per workspace, not just hidden or visible globally, which is nice. Since the bar/dock window is identified by the `_NET_WM_WINDOW_TYPE_DOCK` window type, I would assume a toggle like this would be doable for things like polybar or lemonbar as well as the default dock.

Being able to toggle it is a nice way to create a more focused environment on a particular workspace without having to completely kill your bar/dock, fullscreen a window, or hide it on workspaces where you don't need that focused environment.

**Comment by phillbush** [comment]
I can make the dock and other bars hideable on shodc action.
Depending on how easily desktop-based visibility can be achieved with scripting (by bind a keypress to the `shodc` command to set the dock/bars to visible and the command to change the desktop), then I will not implement it on `shod` itself.  If that shows to be hard to achieve by scripting, I can implement it on shod itself.

I have a few ideas for shod and will work on its code again with new features and bug features soon.

**Comment by phillbush** [comment]
I have been working a lot on shod lately. One change (which I still need to document) is setting dock/bar states.

The following lists dock and bar IDs:

```
$ shodc docks
0x00c00043
0x02000005
```

For a long list (the first column is still not implemented):

```
$ shodc docks -l
--------        65x768+1918+0   0x00c00043      shod's dock
--------        1024x30+0+1476  0x02000005      tint2
```

So, to make the shod dock not take maximized space and be below windows (the default is to take maximized space and be above windows):

```
$ shodc state -RM 0x00c00043
$ shodc state -Ab 0x00c00043
```

**Note on `shodc state`:** I am not happy with the syntax of `shodc state`, it will probably be changed to a more verbose command.

That is:
```
$ shodc state -remove 0x00c00043 maximized
```
...rather than:
```
$ shodc state -RM 0x00c00043
```

**Comment by BanchouBoo** [comment]
Have you put any thought into making the bar and dock state unique per desktop, so that they can always be minimized/hidden (or any other state) on specific desktops without having to apply it globally?

**Comment by phillbush** [comment]
> Have you put any thought into making the bar and dock state unique per desktop, so that they can always be minimized/hidden (or any other state) on specific desktops without having to apply it globally?

Per-desktop state is the hardest path; it would require re-configuring all properties of the bar/dock on every desktop change. Per-desktop visibility is easier.

But in the end, per-desktop visibility would be exactly like dwm's tag system, in which the user can set visibility per-tag.  But if I add tags for dock/bars, why should regular clients still use the regular desktop/workspace behavior?

I have been inspired by z3bra's [post on workspaces and tags](https://web.archive.org/web/20211205144920/http://blog.z3bra.org/2014/11/avoid-workspaces.html) into considering drop workspaces altogether and adopt the tag system for all types of windows. And I will probably do that, depending on its feasibility.

For now, regular windows are still visible on a single desktop at a time (except when sticky); while bars/dock are still visible on all desktops.
I will bump this thread if/when the tag system get implemented.
