### ISSUE TITLE
Strange behaviour when moving window between monitors

### ISSUE THREAD

**Issue by webbongithub** [phillbush/shod#40]
(This is on 2.5.0, with a patch to decrease the rendering time to 16ms)

Moving the window between multiple monitors causes it to jump, with the cursor left where you'd expect it to be such that the window isn't under the cursor. I've disabled snapping. If this is intended behaviour, should the cursor warp? I was a bit lazy in laying the video out, it jumps right as half the window is on the other monitor.

https://user-images.githubusercontent.com/129693493/233756115-d9b20304-c2a4-4e9c-b847-f8466e230912.mp4

**Comment by phillbush** [comment]
Fixed. Thanks for reporting the bug!

It was happening because the function that updates the monitor and desktop of the container repositions the container to be visible on the new monitor. But since the container replacement is being done manually, and not by shodc, the automatic repositioning is not what the user wants.
