### ISSUE TITLE
Add an "always on top" layer above the fullscreen layer

### ISSUE THREAD

**Issue by BanchouBoo** [phillbush/shod#43]
Sometimes when I play games I find myself wishing I could make windows that exist over the top of the game window, but this is impossible if the game is fullscreened. I only have one monitor so it'd be a nice way to for example have notes or put a small chat window on my screen or overlay a video while I'm doing some mindless task.

**Comment by phillbush** [comment]
That can be done by simply reordering [the entries in this `enum` ](https://github.com/phillbush/shod/blob/f05cef75105f6fc31c2fc5f46ccf950aa84e663e/shod.h#L137), placing `LAYER_ABOVE` after `LAYER_FULLSCREEN`. Just be aware that `LAYER_LAST` should be the last.

Particularly, I rarely use the above layer, and never use the below layer at all. I have added them to conform with EWMH, and because they were easy to implement. So I see no problem in changing it. I can move the above layer after fullscreen (moving the menu layer as well, since it may be needed); or create a new "top" layer above everything, if the former breaks someone workflow.  What do you think?

**Comment by phillbush** [comment]
Just be aware that, the way they are implemented, fullscreen windows are focus-stealing. So you may not be able to focus a window on other layers when a fullscreen window is focused.

**Comment by BanchouBoo** [comment]
> Particularly, I rarely use the above layer, and never use the below layer at all. I have added them to conform with EWMH, and because they were easy to implement. So I see no problem in changing it. I can move the above layer after fullscreen (moving the menu layer as well, since it may be needed); or create a new "top" layer above everything, if the former breaks someone workflow. What do you think?

I don't personally see myself ever using below or ever wanting to use above without also drawing over fullscreen windows so just moving it higher would be fine by me, but I don't see a downside to making an entirely new layer for it as long as it's not too much work to implement (I wouldn't expect it to be a difficult inclusion but I haven't explored the source code much). So either solution works for me.

> Just be aware that, the way they are implemented, fullscreen windows are focus-stealing. So you may not be able to focus a window on other layers when a fullscreen window is focused.

That's fine, probably even preferable in some cases.

**Comment by phillbush** [comment]
I dropped the idea of focus-hungry fullscreen windows on a special layer above everything else (bars, regular windows, etc) after checking how wmaker and other stacking window managers handle fullscreen:

* When a window goes fullscreen, it is stretched to fit the entire monitor, but is kept at its window layer.
* When a fullscreen window is active/focused, the only thing that happens is that the dock and bars are hidden. Doing alt-tab into a non-fullscreen window will focus that window and show back the dock/bars.

The only problem that may arise is when the user focus a *below* window from fullscreen window: the below one will never appear (although it has keyboard focus), because it is obscured by the fullscreen one.
