### ISSUE TITLE
Feature Request: Containers Snap for Lateral Screen Borders

### ISSUE THREAD

**Issue by wesbluemarine** [phillbush/shod#46]
Top snap for full screen is already there.
Would be possible to implement lateral border snap for having two vertical maximized containers of the same size?

**Comment by phillbush** [comment]
(I think we have talked about that on IRC before)

Shod does tiling in a non conventional way. Instead of tiling windows on the screen, it tiles window on floating containers.
What you're proposing (to snap a container to the left edge of the screen and make it tile to the border) would require implementing container-level tiling, which is not how Shod works.
