### ISSUE TITLE
Font setting

### ISSUE THREAD

**Issue by vaskark** [phillbush/shod#5]
Hi. This is a really neat wm, so thanks. I have a question about setting a new font for the window title bar. I've tried as many variations as I could think of but none seem to work. Do ttf and bdf (or otb) font formats work? If so, what is the proper syntax?

Thanks.

**Comment by phillbush** [comment]
Hi,  
Until now, shod only supported the old X11 fonts.  
But because of this issue, I have just implemented support for Xft fonts in a [proper branch](https://github.com/phillbush/shod/tree/xft).  
I will merge xft into master after testing the changes and be confident they are OK.

**NOTE:** Shod does still not support multiple/fallback fonts. Only a single font is supported for now.

**Comment by vaskark** [comment]
Thanks so much! I really didn't expect you to do that. I just figured I was doing something wrong.

Looking forward to the updates and further development.
Once again, many thanks..
