### ISSUE TITLE
ablility to resize dialog windows

### ISSUE THREAD

**Issue by aspizu** [phillbush/shod#9]

**Comment by phillbush** [comment]
Yeah, I can implement that feature.

The way I'm thinking is to add a single resize handle in the bottom right corner (rather than in all four corners like in regular windows).  Since dialogs are centered on the main window, the direction of resizing makes no difference: the dialog window will be centered while resized.  
What do you think?

**Comment by aspizu** [comment]
sure

**Comment by phillbush** [comment]
Detached dialogs can now be resized with Alt + right mouse button. Embedded dialogs are still imovable and unresizable.  
I decided to not add handles in the borders (it would require rewriting too much code; and handles kinda do not fit on dialogs).
